version: '3.8'

services:
  web:
    build: .
    image: aceest_fitness_flask
    container_name: aceest_fitness_flask_container
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: python app.py